In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## CARREGAMENTO

In [56]:
df = pd.read_parquet('../data/raw/sih_PR_2023_01.parquet')
print (f"Dados carregados: {len(df)} linhas")

Dados carregados: 1022423 linhas

In [57]:
print("----------DATASET-----------")
print(f"Quantidade de colunas:{df.shape[1]}")
print(f"Registros: {len(df):,}")

----------DATASET-----------
Quantidade de colunas:36
Registros: 1,022,423

NAO USAREMOS TODAS AS 36 COLUNAS, SÃO MUITAS. PRECISA DE UM TRATAMENTO DE TIPO POIS TODAS ESTÃO COMO OBJECT, ATRAPALHANDO NOSSAS FUTURAS MÉTRICAS.

## ESTRURA

In [58]:
print(f"Colunas:{df.columns.tolist()}")

Colunas:['SP_GESTOR', 'SP_UF', 'SP_AA', 'SP_MM', 'SP_CNES', 'SP_NAIH', 'SP_PROCREA', 'SP_DTINTER', 'SP_DTSAIDA', 'SP_NUM_PR', 'SP_TIPO', 'SP_CPFCGC', 'SP_ATOPROF', 'SP_TP_ATO', 'SP_QTD_ATO', 'SP_PTSP', 'SP_NF', 'SP_VALATO', 'SP_M_HOSP', 'SP_M_PAC', 'SP_DES_HOS', 'SP_DES_PAC', 'SP_COMPLEX', 'SP_FINANC', 'SP_CO_FAEC', 'SP_PF_CBO', 'SP_PF_DOC', 'SP_PJ_DOC', 'IN_TP_VAL', 'SEQUENCIA', 'REMESSA', 'SERV_CLA', 'SP_CIDPRI', 'SP_CIDSEC', 'SP_QT_PROC', 'SP_U_AIH']

In [59]:
print(f"Tipos: {df.dtypes}")

Tipos: SP_GESTOR     object
SP_UF         object
SP_AA         object
SP_MM         object
SP_CNES       object
SP_NAIH       object
SP_PROCREA    object
SP_DTINTER    object
SP_DTSAIDA    object
SP_NUM_PR     object
SP_TIPO       object
SP_CPFCGC     object
SP_ATOPROF    object
SP_TP_ATO     object
SP_QTD_ATO    object
SP_PTSP       object
SP_NF         object
SP_VALATO     object
SP_M_HOSP     object
SP_M_PAC      object
SP_DES_HOS    object
SP_DES_PAC    object
SP_COMPLEX    object
SP_FINANC     object
SP_CO_FAEC    object
SP_PF_CBO     object
SP_PF_DOC     object
SP_PJ_DOC     object
IN_TP_VAL     object
SEQUENCIA     object
REMESSA       object
SERV_CLA      object
SP_CIDPRI     object
SP_CIDSEC     object
SP_QT_PROC    object
SP_U_AIH      object
dtype: object

In [60]:
print(f"\nValores Unicos por Coluna:")
print(df.nunique())

Valores Unicos por Coluna:

SP_GESTOR        31
SP_UF             1
SP_AA             1
SP_MM             1
SP_CNES         284
SP_NAIH       74681
SP_PROCREA     1115
SP_DTINTER      227
SP_DTSAIDA      177
SP_NUM_PR         1
SP_TIPO           1
SP_CPFCGC       360
SP_ATOPROF     2198
SP_TP_ATO         1
SP_QTD_ATO      161
SP_PTSP         176
SP_NF          7913
SP_VALATO     20274
SP_M_HOSP       194
SP_M_PAC        657
SP_DES_HOS        2
SP_DES_PAC        2
SP_COMPLEX        2
SP_FINANC         4
SP_CO_FAEC       12
SP_PF_CBO        77
SP_PF_DOC      7176
SP_PJ_DOC       835
IN_TP_VAL         2
SEQUENCIA     40921
REMESSA          31
SERV_CLA         90
SP_CIDPRI      3588
SP_CIDSEC         1
SP_QT_PROC      161
SP_U_AIH          2
dtype: int64

In [61]:
df.describe(include='all')

,SP_GESTOR,SP_UF,SP_AA,SP_MM,SP_CNES,SP_NAIH,SP_PROCREA,SP_DTINTER,SP_DTSAIDA,SP_NUM_PR,...,SP_PF_DOC,SP_PJ_DOC,IN_TP_VAL,SEQUENCIA,REMESSA,SERV_CLA,SP_CIDPRI,SP_CIDSEC,SP_QT_PROC,SP_U_AIH
count,1022423,1022423,1022423,1022423,1022423,1022423,1022423,1022423,1022423,1022423,...,1022423,1022423,1022423,1022423,1022423,1022423,1022423,1022423,1022423,1022423
unique,31,1,1,1,284,74681,1115,227,177,1,...,7176,835,2,40921,31,90,3588,1,161,2
top,410000,41,2023,01,0015245,4122112375084,0303010037,20230109,20230105,,...,000000000000000,00000000000000,1,8,HE41000001N202301.DTS,000000,O800,0000,1,0
freq,480262,1022423,1022423,1022423,65273,252,56027,20123,23807,1022423,...,714348,206623,816660,415,480262,870485,30795,1022423,562448,947680

## QUALIDADE DOS DADOS

In [62]:
nulos = df.isnull().sum()
nulos_percent = (nulos / len(df))*100

df_nulos = pd.DataFrame({
    'Nulos' : nulos,
    'Percentual' : nulos_percent

}).sort_values('Nulos', ascending=False)
print(f"Valores Nulos por coluna:")
df_nulos

Valores Nulos por coluna:

            Nulos  Percentual
SP_GESTOR       0         0.0
SP_UF           0         0.0
SP_AA           0         0.0
SP_MM           0         0.0
SP_CNES         0         0.0
SP_NAIH         0         0.0
SP_PROCREA      0         0.0
SP_DTINTER      0         0.0
SP_DTSAIDA      0         0.0
SP_NUM_PR       0         0.0
SP_TIPO         0         0.0
SP_CPFCGC       0         0.0
SP_ATOPROF      0         0.0
SP_TP_ATO       0         0.0
SP_QTD_ATO      0         0.0
SP_PTSP         0         0.0
SP_NF           0         0.0
SP_VALATO       0         0.0
SP_M_HOSP       0         0.0
SP_M_PAC        0         0.0
SP_DES_HOS      0         0.0
SP_DES_PAC      0         0.0
SP_COMPLEX      0         0.0
SP_FINANC       0         0.0
SP_CO_FAEC      0         0.0
SP_PF_CBO       0         0.0
SP_PF_DOC       0         0.0
SP_PJ_DOC       0         0.0
IN_TP_VAL       0         0.0
SEQUENCIA       0         0.0
REMESSA         0         0.0
SERV_CLA        0         0.0
SP_CIDPRI       0         0.0
SP_CIDSEC       0         0.0
SP_QT_PROC      0         0.0
SP_U_AIH        0         0.0

NAO TEMOS COLUNAS COM VALORES NULOS

In [63]:
duplicatas = df.duplicated().sum()
print(f"\nRegistros Duplicados:")
print(f"Total de duplicatas: {duplicatas:,}")
if duplicatas > 0:
    print(f"Percentual: {duplicatas / len(df) * 100:.2f}%")
else:
    print("Nenhum registro duplicado encontrado!")

Registros Duplicados:
Total de duplicatas: 72,929
Percentual: 7.13%

In [64]:
# Verificar como são as duplicatas
duplicatas_df = df[df.duplicated(keep=False)]  # keep=False mostra todas as duplicatas
print(f"Registros envolvidos em duplicatas: {len(duplicatas_df):,}")
print(f"Isso representa {len(duplicatas_df) / len(df) * 100:.2f}% dos dados")

# Verificar um exemplo de duplicata
print("\n📋 EXEMPLO DE REGISTROS DUPLICADOS:")
duplicatas_df.head(10)

Registros envolvidos em duplicatas: 103,633
Isso representa 10.14% dos dados

📋 EXEMPLO DE REGISTROS DUPLICADOS:

,SP_GESTOR,SP_UF,SP_AA,SP_MM,SP_CNES,SP_NAIH,SP_PROCREA,SP_DTINTER,SP_DTSAIDA,SP_NUM_PR,...,SP_PF_DOC,SP_PJ_DOC,IN_TP_VAL,SEQUENCIA,REMESSA,SERV_CLA,SP_CIDPRI,SP_CIDSEC,SP_QT_PROC,SP_U_AIH
33,410000,41,2023,01,2729423,4122111644190,0303150050,20221210,20221217,,...,000000000000000,00000006330819,1,33458,HE41000001N202301.DTS,000000,N390,0000,1,0
34,410000,41,2023,01,2729423,4122111644190,0303150050,20221210,20221217,,...,000000000000000,00000006330819,1,33458,HE41000001N202301.DTS,000000,N390,0000,1,0
59,410000,41,2023,01,2729423,4122111644233,0301060088,20221226,20221228,,...,000000000000000,00000006330819,1,33462,HE41000001N202301.DTS,000000,J181,0000,1,0
60,410000,41,2023,01,2729423,4122111644233,0301060088,20221226,20221228,,...,000000000000000,00000006330819,1,33462,HE41000001N202301.DTS,000000,J181,0000,1,0
382,410000,41,2023,01,4055748,4122111125187,0310010039,20221130,20221202,,...,000000000000000,00000004055748,1,34114,HE41000001N202301.DTS,000000,O800,0000,1,0
384,410000,41,2023,01,4055748,4122111125187,0310010039,20221130,20221202,,...,000000000000000,00000004055748,1,34114,HE41000001N202301.DTS,000000,O800,0000,1,0
468,410000,41,2023,01,4055748,4122111646367,0303140151,20221228,20230102,,...,000000000000000,00000004055748,1,34254,HE41000001N202301.DTS,000000,J189,0000,1,0
472,410000,41,2023,01,4055748,4122111646367,0303140151,20221228,20230102,,...,000000000000000,00000004055748,1,34254,HE41000001N202301.DTS,000000,J189,0000,1,0
500,410000,41,2023,01,4055748,4122111646565,0303150050,20221230,20230103,,...,000000000000000,00000004055748,1,34265,HE41000001N202301.DTS,000000,N390,0000,2,0
501,410000,41,2023,01,4055748,4122111646565,0303150050,20221230,20230103,,...,000000000000000,00000004055748,1,34265,HE41000001N202301.DTS,000000,N390,0000,2,0

In [65]:
# 4.6.1 ANÁLISE DETALHADA DE DUPLICATAS

print("Análise Duplicatas")

# 1. Ver quais colunas têm maior variação nas duplicatas
print("\n1. COLUNAS COM MAIOR NÚMERO DE VALORES ÚNICOS:")
print("   (Colunas com muitos valores únicos indicam que as duplicatas são reais)")
print(df.nunique().sort_values(ascending=False).head(10))

# 2. Identificar padrões - quais colunas são iguais nas duplicatas
print("\n2. ANALISANDO UM GRUPO DE DUPLICATAS:")
# Pegar o primeiro grupo de duplicatas
duplicatas_df = df[df.duplicated(keep=False)]
primeiro_grupo = duplicatas_df.groupby(df.columns.tolist()).size().head(1)
print(f"   Grupo de duplicatas encontrado:")
print(primeiro_grupo)

# 3. Mostrar um exemplo de registros duplicados
print("\n3. EXEMPLO DE REGISTROS DUPLICADOS (primeiro grupo):")
colunas_para_ver = ['SP_CNES', 'SP_NAIH', 'SP_DTINTER', 'SP_VALATO', 'SP_CIDPRI']
primeiro_grupo = duplicatas_df[duplicatas_df.duplicated(keep=False)].head(3)
print(primeiro_grupo[colunas_para_ver])

# 4. Verificar se as duplicatas são AIHs diferentes (mesmo paciente, procedimentos diferentes)
print("\n4. VERIFICANDO SE SÃO PROCEDIMENTOS DIFERENTES:")
# Verificar se a SP_NAIH (número da AIH) é igual ou diferente
aih_duplicadas = duplicatas_df['SP_NAIH'].value_counts().head(10)
print(f"   AIHs com múltiplos registros:")
print(aih_duplicadas[aih_duplicadas > 1])

# 5. Verificar se há mais de um procedimento por AIH
print("\n5. PROCEDIMENTOS POR AIH (exemplo):")
aih_exemplo = duplicatas_df['SP_NAIH'].value_counts().index[0]
print(f"AIH: {aih_exemplo}")
print(f"Registros para esta AIH:")
display(duplicatas_df[duplicatas_df['SP_NAIH'] == aih_exemplo])

Análise Duplicatas

1. COLUNAS COM MAIOR NÚMERO DE VALORES ÚNICOS:
   (Colunas com muitos valores únicos indicam que as duplicatas são reais)

SP_NAIH       74681
SEQUENCIA     40921
SP_VALATO     20274
SP_NF          7913
SP_PF_DOC      7176
SP_CIDPRI      3588
SP_ATOPROF     2198
SP_PROCREA     1115
SP_PJ_DOC       835
SP_M_PAC        657
dtype: int64

2. ANALISANDO UM GRUPO DE DUPLICATAS:
   Grupo de duplicatas encontrado:
SP_GESTOR  SP_UF  SP_AA  SP_MM  SP_CNES  SP_NAIH        SP_PROCREA  SP_DTINTER  SP_DTSAIDA  SP_NUM_PR  SP_TIPO  SP_CPFCGC       SP_ATOPROF  SP_TP_ATO  SP_QTD_ATO  SP_PTSP  SP_NF  SP_VALATO  SP_M_HOSP  SP_M_PAC  SP_DES_HOS  SP_DES_PAC  SP_COMPLEX  SP_FINANC  SP_CO_FAEC  SP_PF_CBO  SP_PF_DOC        SP_PJ_DOC       IN_TP_VAL  SEQUENCIA  REMESSA                SERV_CLA  SP_CIDPRI  SP_CIDSEC  SP_QT_PROC  SP_U_AIH
410000     41     2023   01     0013633  4122110044745  0406030049  20221110    20221130                        00000000013633  0302040021             1           0               7.00       410400     410720    0           1           03          04         040076      223605     708408206478368  00000000013633  1          5952       HE41000001N202301.DTS  126004    I214       0000       1           0           2
dtype: int64

3. EXEMPLO DE REGISTROS DUPLICADOS (primeiro grupo):
    SP_CNES        SP_NAIH SP_DTINTER SP_VALATO SP_CIDPRI
33  2729423  4122111644190   20221210      0.00      N390
34  2729423  4122111644190   20221210      0.00      N390
59  2729423  4122111644233   20221226      0.00      J181

4. VERIFICANDO SE SÃO PROCEDIMENTOS DIFERENTES:
   AIHs com múltiplos registros:
SP_NAIH
4123100188064    213
4123100187448    210
4123106936003    193
4122101946413    190
4123100185700    182
4122112375084    171
4123100188042    170
4123100117059    159
4123100361370    154
4123100117026    153
Name: count, dtype: int64

5. PROCEDIMENTOS POR AIH (exemplo):
AIH: 4123100188064
Registros para esta AIH:

,SP_GESTOR,SP_UF,SP_AA,SP_MM,SP_CNES,SP_NAIH,SP_PROCREA,SP_DTINTER,SP_DTSAIDA,SP_NUM_PR,...,SP_PF_DOC,SP_PJ_DOC,IN_TP_VAL,SEQUENCIA,REMESSA,SERV_CLA,SP_CIDPRI,SP_CIDSEC,SP_QT_PROC,SP_U_AIH
21902,412550,41,2023,01,2753278,4123100188064,0303010037,20230103,20230129,,...,000000000000000,00000006994636,1,843,HM41255001N202301.DTS,000000,A419,0000,1,0
21903,412550,41,2023,01,2753278,4123100188064,0303010037,20230103,20230129,,...,000000000000000,00000006994636,1,843,HM41255001N202301.DTS,000000,A419,0000,1,0
21904,412550,41,2023,01,2753278,4123100188064,0303010037,20230103,20230129,,...,000000000000000,00000006994636,1,843,HM41255001N202301.DTS,000000,A419,0000,1,0
21905,412550,41,2023,01,2753278,4123100188064,0303010037,20230103,20230129,,...,000000000000000,00000006994636,1,843,HM41255001N202301.DTS,000000,A419,0000,1,0
21906,412550,41,2023,01,2753278,4123100188064,0303010037,20230103,20230129,,...,000000000000000,00000006994636,1,843,HM41255001N202301.DTS,000000,A419,0000,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844755,412550,41,2023,01,2753278,4123100188064,0303010037,20230103,20230129,,...,000000000000000,00000006994636,1,843,HM41255001N202301.DTS,000000,A419,0000,1,0
844756,412550,41,2023,01,2753278,4123100188064,0303010037,20230103,20230129,,...,000000000000000,00000006994636,1,843,HM41255001N202301.DTS,000000,A419,0000,1,0
844757,412550,41,2023,01,2753278,4123100188064,0303010037,20230103,20230129,,...,000000000000000,00000006994636,1,843,HM41255001N202301.DTS,000000,A419,0000,1,0
844758,412550,41,2023,01,2753278,4123100188064,0303010037,20230103,20230129,,...,000000000000000,00000006994636,1,843,HM41255001N202301.DTS,000000,A419,0000,1,0
844759,412550,41,2023,01,2753278,4123100188064,0303010037,20230103,20230129,,...,000000000000000,00000006994636,1,843,HM41255001N202301.DTS,000000,A419,0000,1,0

In [66]:
# ==========================================
# VERIFICANDO SE AS DUPLICATAS SÃO DO MESMO PACIENTE
# ==========================================
print("🔍 VERIFICANDO PACIENTES NAS DUPLICATAS")

# 1. Pegar um exemplo de AIH com múltiplos registros
duplicatas_df = df[df.duplicated(keep=False)]
if len(duplicatas_df) > 0:
    # Pegar a AIH com mais registros
    aih_exemplo = duplicatas_df['SP_NAIH'].value_counts().index[0]
    exemplos = df[df['SP_NAIH'] == aih_exemplo]
    
    print(f"\nAIH EXEMPLO: {aih_exemplo}")
    print(f"Total de registros: {len(exemplos)}")
    print(f"Colunas que poderiam identificar pacientes diferentes:")
    
    # Verificar colunas de identificação do paciente
    colunas_paciente = ['SP_CPFCGC', 'SP_M_PAC', 'SP_DES_PAC']
    for col in colunas_paciente:
        if col in exemplos.columns:
            print(f"     - {col}: {exemplos[col].nunique()} valor(es) único(s)")
    
    # Verificar se há pacientes diferentes
    if 'SP_CPFCGC' in exemplos.columns:
        pacientes_unicos = exemplos['SP_CPFCGC'].nunique()
        if pacientes_unicos == 1:
            print(f"\nCONFIRMADO: É o MESMO paciente!")
            print(f"CPF/CNPJ único: {exemplos['SP_CPFCGC'].iloc[0]}")
        else:
            print(f"\nALERTA: Múltiplos pacientes para mesma AIH!")
            print(f"Total de pacientes: {pacientes_unicos}")
            print(f"Isso é um erro grave!")
    
    # 2. Mostrar os registros
    print(f"\nREGISTROS DA AIH {aih_exemplo}:")
    display(exemplos[['SP_NAIH', 'SP_CPFCGC', 'SP_M_PAC', 'SP_VALATO', 'SP_CIDPRI', 'SP_QT_PROC']])
    
    # 3. Diagnóstico final
    print("\n" + "="*60)
    print("📋 DIAGNÓSTICO FINAL")
    print("="*60)
    
    if 'SP_CPFCGC' in exemplos.columns and exemplos['SP_CPFCGC'].nunique() == 1:
        print("MESMO PACIENTE - As duplicatas são procedimentos diferentes da mesma internação")
        print("Manter duplicatas (remover apenas duplicatas exatas)")
    else:
        print("PACIENTES DIFERENTES - Possível erro de sistema")
        print("Investigar mais a fundo antes de decidir")

🔍 VERIFICANDO PACIENTES NAS DUPLICATAS

AIH EXEMPLO: 4123100188064
Total de registros: 243
Colunas que poderiam identificar pacientes diferentes:
     - SP_CPFCGC: 1 valor(es) único(s)
     - SP_M_PAC: 1 valor(es) único(s)
     - SP_DES_PAC: 1 valor(es) único(s)

CONFIRMADO: É o MESMO paciente!
CPF/CNPJ único: 00000002753278

REGISTROS DA AIH 4123100188064:

              SP_NAIH       SP_CPFCGC SP_M_PAC SP_VALATO SP_CIDPRI SP_QT_PROC
21902   4123100188064  00000002753278   412550      0.00      A419          1
21903   4123100188064  00000002753278   412550      0.00      A419          1
21904   4123100188064  00000002753278   412550      0.00      A419          1
21905   4123100188064  00000002753278   412550      0.00      A419          1
21906   4123100188064  00000002753278   412550      0.00      A419          1
...               ...             ...      ...       ...       ...        ...
844755  4123100188064  00000002753278   412550      0.00      A419          1
844756  4123100188064  00000002753278   412550      0.00      A419          1
844757  4123100188064  00000002753278   412550      0.00      A419          1
844758  4123100188064  00000002753278   412550      0.00      A419          1
844759  4123100188064  00000002753278   412550      0.00      A419          1

[243 rows x 6 columns]

============================================================
📋 DIAGNÓSTICO FINAL
============================================================
MESMO PACIENTE - As duplicatas são procedimentos diferentes da mesma internação
Manter duplicatas (remover apenas duplicatas exatas)

In [67]:
# ==========================================
# PASSO 1: REMOVER DUPLICATAS EXATAS
# ==========================================

print("\n" + "="*60)
print("🧹 REMOVENDO DUPLICATAS EXATAS")
print("="*60)

# Contar antes
antes = len(df)
print(f"📊 Registros ANTES: {antes:,}")

# Remover duplicatas exatas
df = df.drop_duplicates()

# Contar depois
depois = len(df)
removidos = antes - depois
print(f"📊 Registros DEPOIS: {depois:,}")
print(f"🗑️ Duplicatas removidas: {removidos:,} ({removidos/antes*100:.2f}%)")

============================================================
🧹 REMOVENDO DUPLICATAS EXATAS
============================================================
📊 Registros ANTES: 1,022,423

📊 Registros DEPOIS: 949,494
🗑️ Duplicatas removidas: 72,929 (7.13%)

In [68]:
colunas_essenciais = [
       'SP_GESTOR',   # Código do Município
    'SP_CNES',     # ID do Hospital
    'SP_CIDPRI',   # Código CID-10 da doença
    'SP_DTINTER',  # Data de Internação
    'SP_DTSAIDA',  # Data de Saída
    'SP_VALATO',   # Valor do Ato Profissional
    'SP_M_PAC',    # Município do Paciente
    'SP_AA',       # Ano
    'SP_MM'        # Mês
]

df_filtrado = df[colunas_essenciais].copy()
df_filtrado

,SP_GESTOR,SP_CNES,SP_CIDPRI,SP_DTINTER,SP_DTSAIDA,SP_VALATO,SP_M_PAC,SP_AA,SP_MM
0,410000,2729385,I64,20230126,20230127,0.00,411270,2023,01
1,410000,2729385,I64,20230126,20230127,0.00,411270,2023,01
2,410000,2729385,K838,20230128,20230130,41.95,410980,2023,01
3,410000,2729385,K838,20230128,20230130,16.00,410980,2023,01
4,410000,2729385,K838,20230128,20230130,16.78,410980,2023,01
...,...,...,...,...,...,...,...,...,...
1022418,410000,2742039,T012,20230113,20230114,33.34,411930,2023,01
1022419,410000,2742039,I64,20230105,20230105,33.34,411930,2023,01
1022420,410000,2742039,T012,20230110,20230110,33.34,411930,2023,01
1022421,410000,2742039,T012,20230103,20230104,33.34,411930,2023,01
1022422,410000,2742039,T012,20230105,20230106,33.34,353480,2023,01

As colunas selecionadas são essenciais para responder às perguntas de negócio:

1. **SP_GESTOR**: Permite análise por município gestor (quem financiou o atendimento)
2. **SP_CNES**: Permite integração com dados de leitos (CNES) e análise por hospital
3. **SP_CIDPRI**: Permite análise das principais causas de internação
4. **SP_DTINTER/SP_DTSAIDA**: Permite calcular tempo de permanência e análises temporais
5. **SP_VALATO**: Permite análise de custos e eficiência
6. **SP_M_PAC**: Permite calcular deslocamento de pacientes (demanda regional)
7. **SP_AA/SP_MM**: Permite filtrar por período e análises sazonais

As colunas removidas são operacionais ou administrativas, não necessárias para os KPIs do dashboard.

In [69]:
df_filtrado['SP_DTINTER'] = pd.to_datetime(df_filtrado['SP_DTINTER'], format='%Y%m%d', errors='coerce')
df_filtrado['SP_DTSAIDA'] = pd.to_datetime(df_filtrado['SP_DTSAIDA'], format='%Y%m%d', errors ='coerce')

df_filtrado['SP_VALATO'] = pd.to_numeric(df_filtrado['SP_VALATO'], errors = 'coerce' )

df_filtrado['SP_AA'] = pd.to_numeric(df_filtrado['SP_AA'], errors='coerce').fillna(0).astype(int)
df_filtrado['SP_MM'] = pd.to_numeric(df_filtrado['SP_MM'], errors='coerce').fillna(0).astype(int)

df_filtrado.dtypes

SP_GESTOR             object
SP_CNES               object
SP_CIDPRI             object
SP_DTINTER    datetime64[ns]
SP_DTSAIDA    datetime64[ns]
SP_VALATO            float64
SP_M_PAC              object
SP_AA                  int64
SP_MM                  int64
dtype: object

In [70]:
dicionario_colunas = {
    'SP_CNES': 'id_hospital',
    'SP_GESTOR': 'codigo_municipio',
    'SP_CIDPRI': 'codigo_diagnostico',
    'SP_DTINTER': 'data_internacao',
    'SP_DTSAIDA': 'data_saida',
    'SP_VALATO': 'valor_procedimento',
    'SP_M_PAC': 'codigo_municipio_paciente',
    'SP_AA': 'ano_competencia',
    'SP_MM': 'mes_competencia'
}

df_filtrado.rename(columns=dicionario_colunas, inplace=True)
df_filtrado

,codigo_municipio,id_hospital,codigo_diagnostico,data_internacao,data_saida,valor_procedimento,codigo_municipio_paciente,ano_competencia,mes_competencia
0,410000,2729385,I64,2023-01-26,2023-01-27,0.00,411270,2023,1
1,410000,2729385,I64,2023-01-26,2023-01-27,0.00,411270,2023,1
2,410000,2729385,K838,2023-01-28,2023-01-30,41.95,410980,2023,1
3,410000,2729385,K838,2023-01-28,2023-01-30,16.00,410980,2023,1
4,410000,2729385,K838,2023-01-28,2023-01-30,16.78,410980,2023,1
...,...,...,...,...,...,...,...,...,...
1022418,410000,2742039,T012,2023-01-13,2023-01-14,33.34,411930,2023,1
1022419,410000,2742039,I64,2023-01-05,2023-01-05,33.34,411930,2023,1
1022420,410000,2742039,T012,2023-01-10,2023-01-10,33.34,411930,2023,1
1022421,410000,2742039,T012,2023-01-03,2023-01-04,33.34,411930,2023,1
1022422,410000,2742039,T012,2023-01-05,2023-01-06,33.34,353480,2023,1

In [71]:
df_filtrado['dias_internacao'] = (df_filtrado['data_saida'] - df_filtrado['data_internacao']).dt.days
df_filtrado.head(2)

,codigo_municipio,id_hospital,codigo_diagnostico,data_internacao,data_saida,valor_procedimento,codigo_municipio_paciente,ano_competencia,mes_competencia,dias_internacao
0,410000,2729385,I64,2023-01-26,2023-01-27,0.0,411270,2023,1,1
1,410000,2729385,I64,2023-01-26,2023-01-27,0.0,411270,2023,1,1

In [72]:
df_filtrado['paciente_viajou'] = df_filtrado['codigo_municipio_paciente'] != df_filtrado['codigo_municipio']
df_filtrado.head(2)

,codigo_municipio,id_hospital,codigo_diagnostico,data_internacao,data_saida,valor_procedimento,codigo_municipio_paciente,ano_competencia,mes_competencia,dias_internacao,paciente_viajou
0,410000,2729385,I64,2023-01-26,2023-01-27,0.0,411270,2023,1,1,True
1,410000,2729385,I64,2023-01-26,2023-01-27,0.0,411270,2023,1,1,True

In [73]:
df_filtrado['dia_semana'] = (df_filtrado['data_internacao']).dt.day_name()
df_filtrado.head()

,codigo_municipio,id_hospital,codigo_diagnostico,data_internacao,data_saida,valor_procedimento,codigo_municipio_paciente,ano_competencia,mes_competencia,dias_internacao,paciente_viajou,dia_semana
0,410000,2729385,I64,2023-01-26,2023-01-27,0.00,411270,2023,1,1,True,Thursday
1,410000,2729385,I64,2023-01-26,2023-01-27,0.00,411270,2023,1,1,True,Thursday
2,410000,2729385,K838,2023-01-28,2023-01-30,41.95,410980,2023,1,2,True,Saturday
3,410000,2729385,K838,2023-01-28,2023-01-30,16.00,410980,2023,1,2,True,Saturday
4,410000,2729385,K838,2023-01-28,2023-01-30,16.78,410980,2023,1,2,True,Saturday

In [74]:
df_filtrado['mes_ano'] = df_filtrado['data_internacao'].dt.to_period('M')
df_filtrado.head(2)

,codigo_municipio,id_hospital,codigo_diagnostico,data_internacao,data_saida,valor_procedimento,codigo_municipio_paciente,ano_competencia,mes_competencia,dias_internacao,paciente_viajou,dia_semana,mes_ano
0,410000,2729385,I64,2023-01-26,2023-01-27,0.0,411270,2023,1,1,True,Thursday,2023-01
1,410000,2729385,I64,2023-01-26,2023-01-27,0.0,411270,2023,1,1,True,Thursday,2023-01

In [75]:
df_filtrado['tipo_dia'] = df_filtrado['dia_semana'].apply(lambda x: 'Fim de Semana' if x in ['Saturday', 'Sunday'] else 'Dia Útil')
df_filtrado.head(2)

,codigo_municipio,id_hospital,codigo_diagnostico,data_internacao,data_saida,valor_procedimento,codigo_municipio_paciente,ano_competencia,mes_competencia,dias_internacao,paciente_viajou,dia_semana,mes_ano,tipo_dia
0,410000,2729385,I64,2023-01-26,2023-01-27,0.0,411270,2023,1,1,True,Thursday,2023-01,Dia Útil
1,410000,2729385,I64,2023-01-26,2023-01-27,0.0,411270,2023,1,1,True,Thursday,2023-01,Dia Útil

In [76]:
total_internacoes = len(df_filtrado)
total_viajaram = df_filtrado['paciente_viajou'].sum()
total_nao_viajaram = total_internacoes - total_viajaram
porcentagem_deslocamento = (total_viajaram / total_internacoes) * 100

print(" --- RELATÓRIO DE PRESSÃO REGIONAL ---")
print(f"• Total de atendimentos analisados: {total_internacoes}")
print(f"• Pacientes atendidos fora de sua cidade natal: {total_viajaram}")
print(f"• Taxa de evasão municipal (pacientes que viajaram): {porcentagem_deslocamento:.2f}%")
print("-----------------------------------------\n")

 --- RELATÓRIO DE PRESSÃO REGIONAL ---
• Total de atendimentos analisados: 949494
• Pacientes atendidos fora de sua cidade natal: 643541
• Taxa de evasão municipal (pacientes que viajaram): 67.78%
-----------------------------------------